- name: import prometheus exporter setup tasks
  become: yes
  import_tasks: prometheus_exporter.yml
  tags:
    - monitoring
    - prometheus
    - prometheus_exporter

- name: import ansible facts configuration tasks
  import_tasks: fact.yml
  become: yes
  tags:
    - monitoring
    - prometheus
    - prometheus_exporter
