#!/bin/bash
set -o errexit
set -o nounset

# Configuration / defaults
xsrv_clone_dir="${XSRV_CLONE_DIR:=$HOME/.local/share/xsrv/git}"
projects_dir="${XSRV_PROJECTS_DIR:=$HOME/playbooks}"
editor="${EDITOR:=nano}"
ansible_tags="${TAGS:-}"
pager="${PAGER:=nano --syntax=YAML --view +1 -}"
version="1.5.0"
ansible_version="5.2.0"
xsrv_git_url="https://gitlab.com/nodiscc/xsrv"
xsrv_upgrade_channel="${XSRV_UPGRADE_CHANNEL:=release}"
local_backups_dir="data/backups"
ascii_banner="  ╻ ╻┏━┓┏━┓╻ ╻
░░╺╋╸┗━┓┣┳┛┃┏┛
  ╹ ╹┗━┛╹┗╸┗┛ v${version}"

### Helpers ###

function check_project_exists() {
    # check that the directory for the specified playbook exists, exit with error if not
    if [[ ! -e "$project_dir" ]]; then
        echo "[xsrv] ERROR: project $project_dir does not exist"; exit 1;
    fi
}

function _check_host_name() {
    # check if host_vars files exist for a host, set host_vars_file and host_vault_file global variables
    check_project_exists
    if [[ -z "$host_name" ]]; then
        host_vars_dirs=$(find "$projects_dir/$project_name/host_vars/" -maxdepth 1 -type d)
        host_name="${host_vars_dirs##*/}"
        echo "[xsrv] INFO: no host name provided, using $host_name as host name"
        if [[ ! $(echo "$host_name" | wc -l) -eq 1 ]]; then
            echo "[xsrv] ERROR: no host name specified and multiple hosts found in project"; exit 1
        fi
    fi
    host_vars_file="$projects_dir/$project_name/host_vars/$host_name/$host_name.yml"
    host_vault_file="$projects_dir/$project_name/host_vars/$host_name/$host_name.vault.yml"
    if [[ ! -f "$host_vars_file" ]]; then
        echo "[xsrv] ERROR: $host_vars_file does not exist"; exit 1
    fi
}

function check_group_name() {
    # check if group_vars files exist for a group, set group_vars_file global variable
    check_project_exists
    group_name="$host_name"
    if [[ -z "$group_name" ]]; then
        echo "[xsrv] INFO: no group name provided, editing variables for group 'all'"
        group_name="all"
    fi
    group_vars_file="$projects_dir/$project_name/group_vars/$group_name.yml"
    if [[ ! -f "$group_vars_file" ]]; then
        echo "[xsrv] INFO: $group_vars_file does not exist, will be created";
    fi
}

function create_venv() {
    echo "[xsrv] INFO: creating virtualenv in $venv_dir"
    mkdir -p "$venv_dir"
    python3 -m venv "$venv_dir"
    source "$venv_dir/bin/activate"
    echo "[xsrv] INFO: installing ansible in $venv_dir"
    pip3 install wheel
    pip3 install ansible=="$ansible_version" netaddr
}

function init_venv() {
    # check if a working ansible virtualenv exists,
    # check if the installed ansible version matches the expected version,
    # otherwise create/activate the virtualenv and install ansible
    check_project_exists
    {
        source "$venv_dir/bin/activate" 2>/dev/null
        ansible_installed_version=$(pip3 show ansible|grep '^Version' | awk -F' ' '{print $2}')
        [ "$ansible_installed_version" == "$ansible_version" ]
    } || create_venv
}

function _get_host_var() {
    # get a host var using ansible -m debug | grep
    # $1: the variable to get, filters allowed (example: "ansible_ssh_port|default(22)")
    (cd "$project_dir" && ansible --one-line \
      --inventory "$project_dir"/inventory.yml \
      --module-name debug --args \
      "msg={{ $1 }}" "$host_name" | \
      grep -oP '(?<="msg": ").*(?="})')
}

function gen_vault_password_file() {
    # generate a random password for ansible-vault and store it in a file
    echo "[xsrv] INFO: Generating random password for ansible-vault"
    openssl rand -base64 32 > "$projects_dir/$project_name/.ansible-vault-password"
    echo "[xsrv] INFO: vault password stored in $projects_dir/$project_name/.ansible-vault-password"
    echo "[xsrv] INFO: Keep this file private! Keep backups of this file!"
}

function gen_random_passwords() {
    # replace CHANGEMEXX values in file $1, where XX is an integer, with random password with length = XX
    host_vault_file="$1"
    if ! command -v pwgen >/dev/null; then
        echo "[xsrv] WARNING: pwgen not installed, unable to generate random passwords for $host_name. Please manually replace any values labeled CHANGEME!"
        return
    fi
    echo "[xsrv] INFO: generating random passwords for $host_name"
    randomized_vault=$(while read -r line; do
        if echo "$line" | grep -E 'CHANGEME[0-9]+' 2>&1 >/dev/null; then
            num_char=$(echo "$line" | grep -oP '(?<=CHANGEME)[0-9]+(?=")')
            echo "$line" | sed -E "s/CHANGEME[0-9]+/$(pwgen -s "$num_char" 1)/"
        else
            echo "$line"
        fi
    done < "$host_vault_file")
    echo "$randomized_vault" > "$host_vault_file"
}


### Commands ###

function help() {
    # show help
    echo "$usage"
    exit 1
}

# shellcheck disable=SC2086 # use arrays for variable expansion, unnecessarily complex
function check() {
    # run ansible playbook in check mode
    check_project_exists
    if [[ -n "$host_name" ]]; then ansible_host_arg="--limit=$host_name"; else ansible_host_arg=""; fi
    if [[ -n "$ansible_tags" ]]; then ansible_tags_arg="--tags=$ansible_tags"; else ansible_tags_arg=""; fi
    cd "$projects_dir/$project_name"
    echo "[xsrv] INFO: deploying main playbook for project $project_name"
    ansible-playbook playbook.yml --check --diff $ansible_tags_arg $ansible_host_arg
}

# shellcheck disable=SC2086 # use arrays for variable expansion, unnecessarily complex
function deploy() {
    # run ansible playbook
    if [[ -n "$host_name" ]]; then ansible_host_arg="--limit=$host_name"; else ansible_host_arg=""; fi
    if [[ -n "$ansible_tags" ]]; then ansible_tags_arg="--tags=$ansible_tags"; else ansible_tags_arg=""; fi
    cd "$projects_dir/$project_name"
    echo "[xsrv] INFO: deploying main playbook for project $project_name"
    ansible-playbook playbook.yml $ansible_tags_arg $ansible_host_arg
}

function edit_playbook() {
    # edit a playbook file
    playbook_file="$projects_dir/$project_name/playbook.yml"
    echo "[xsrv] INFO: opening playbook file $playbook_file"
    $editor "$playbook_file"
}

function edit_inventory() {
    # edit an inventory file
    inventory_file="$projects_dir/$project_name/inventory.yml"
    echo "[xsrv] INFO: opening inventory file $inventory_file"
    $editor "$inventory_file"
}

function edit_requirements() {
    # edit requirements.yml file
    requirements_file="$projects_dir/$project_name/requirements.yml"
    echo "[xsrv] INFO: opening requirements file $requirements_file"
    $editor "$requirements_file"
}

function edit_ansible_cfg() {
    # edit ansible.cfg file
    cfg_file="$projects_dir/$project_name/ansible.cfg"
    echo "[xsrv] INFO: opening requirements file $cfg_file"
    $editor "$cfg_file"
}

function edit_host() {
    # edit a host's vars file
    _check_host_name
    echo "[xsrv] INFO: opening host vars file $host_vars_file"
    $editor "$host_vars_file"
}

function edit_group() {
    # edit group variables
    check_group_name
    echo "[xsrv] INFO: opening group_vars file $group_vars_file"
    $editor "$group_vars_file"
}

function edit_vault() {
    # edit a host's vault file
    _check_host_name
    echo "[xsrv] INFO: opening vault file $host_vault_file"
    cd "$projects_dir/$project_name"
    EDITOR="$editor" ansible-vault edit "$host_vault_file"
}

function legacy_init_playbook() {
    echo "[xsrv] WARNING: init-playbook is deprecated and will be removed in a future release. Use init-project"
    init_project
}

function init_project() {
    # initialize a new project
    if [[ -e "$project_dir" ]]; then
        echo "[xsrv] ERROR: $project_dir already exists"; exit 1
    fi
    mkdir -p "$project_dir"
    init_venv
    upgrade_roles
    echo "[xsrv] INFO: creating files and directories for $project_name"
    templates_dir="$project_dir/ansible_collections/nodiscc/xsrv/playbooks/xsrv"
    cp -rn "$templates_dir"/{ansible.cfg,README.md,requirements.yml,data/,group_vars/,public_keys/,playbooks/} "$project_dir/"
    gen_vault_password_file
    init_host "$host_name"
    echo "[xsrv] INFO: project $project_name initialized in $project_dir"
    echo "[xsrv] INFO: run xsrv deploy to apply configuration now, or xsrv help for more options"
}

function init_host() {
    # add a new host to a project (from template files)
    check_project_exists
    until [[ -n "$host_name" ]]; do
        read -r -p "[xsrv] Host name to add to the $project_name project (ex: my.CHANGEME.org): " host_name
    done
    if [[ -e "$project_dir/host_vars/$host_name" ]]; then
        echo "[xsrv] ERROR: $project_dir/host_vars/$host_name already exists"; exit 1
    fi
    echo "[xsrv] INFO: adding $host_name to the last inventory group"
    echo "    $host_name:" >> "$project_dir/inventory.yml"

    echo "[xsrv] INFO: adding default play for $host_name to project $project_name"
    templates_dir="$project_dir/ansible_collections/nodiscc/xsrv/playbooks/xsrv"
    echo "" >> "$project_dir/playbook.yml"
    sed "s/my.example.org/$host_name/g" "$templates_dir/playbook.yml" >> "$project_dir/playbook.yml"

    echo "[xsrv] INFO: creating default host vars file for $host_name"
    mkdir -p "$project_dir/host_vars/$host_name"
    host_vars_file="$project_dir/host_vars/$host_name/$host_name.yml"
    sed "s/my.example.org/$host_name/g" "$templates_dir/host_vars/my.example.org/my.example.org.yml" > "$host_vars_file"

    echo "[xsrv] INFO: creating default vault file for $host_name"
    host_vault_file="$project_dir/host_vars/$host_name/$host_name.vault.yml"
    sed "s/my.example.org/$host_name/g" "$templates_dir/host_vars/my.example.org/my.example.org.vault.yml" > "$host_vault_file"

    gen_random_passwords "$host_vault_file"
    edit_playbook "$project_name"
    edit_host "$project_name" "$host_name"

    echo "[xsrv] INFO: Encrypting secrets file"
    (cd "$project_dir/" && ansible-vault encrypt "$project_dir/host_vars/$host_name/$host_name.vault.yml")
    edit_vault "$project_name" "$host_name"

    echo "[xsrv] INFO: Host is ready for deployment. Run xsrv deploy $project_name $host_name"
}

function run_shell() {
    # open a SSH shell on a host
    _check_host_name
    ssh_user=$(_get_host_var "ansible_user")
    ssh_port=$(_get_host_var "ansible_ssh_port|default(22)")
    echo "[xsrv] INFO: connecting to $ssh_user@$host_name port $ssh_port"
    ssh_command="ssh -t -p $ssh_port $ssh_user@$host_name $ssh_args"
    $ssh_command
}

function _ls() {
    # list files in the projects directory
    path=${1:-}
    ls "$projects_dir/$path"
}

function fetch_backups() {
    # fetch latest daily backups from the host
    check_project_exists
    ssh_port=$(_get_host_var "ansible_ssh_port|default(22)")
    ssh_user=$(_get_host_var "ansible_user")
    backup_date=$(date "+%Y%m%d_%H%M%S")
    echo "[xsrv] INFO: fetching latest daily backups from $host_name in project $project_name"
    rsync --archive --verbose --rsh="ssh -p $ssh_port" \
      --progress --fake-super --rsync-path='/usr/bin/sudo /usr/bin/rsync' \
      "$ssh_user@$host_name:/var/backups/rsnapshot/daily.0/" \
      "$projects_dir/$project_name/$local_backups_dir/daily.0.$backup_date"
}

function upgrade_roles() {
    check_project_exists
    if [[ ! -f "$project_dir"/requirements.yml ]]; then
        echo "[xsrv] INFO: installing default collection git+$xsrv_git_url,$xsrv_upgrade_channel"
        (cd "$project_dir" && ansible-galaxy collection install --force --collections-path "$project_dir/" git+$xsrv_git_url,$xsrv_upgrade_channel)
    else
        echo "[xsrv] INFO: upgrading collections from requirements.yml"
        (cd "$project_dir" && ansible-galaxy collection install --force -r requirements.yml)
    fi
    create_venv
}

function show_defaults() {
    # show all role defaults
    role=${2:-}
    check_project_exists
    if ! hash "${pager%% *}" 2>/dev/null; then
        echo "[xsrv] INFO: pager command '$pager' unavailable, falling back to 'less'"
        pager="less"
    fi
    if [[ -n "$role" ]]; then
        cat "$project_dir"/ansible_collections/*/*/roles/"$role"/defaults/main.yml | $pager 2>/dev/null
    else
        # shellcheck disable=SC2002
        defaults_header="# List of all role configuration variables, and their default values.\\n# Copy any variable to your host configuration and edit its value there.\\n######################################################\\n\\n"
        default_files=$(find "$project_dir"/ansible_collections/*/*/roles/*/defaults/ -name main.yml)
        defaults_list=$(for file in $default_files; do
            cat "$file"; echo -e "\\n\\n###################################################################"
        done)
        echo -e "$defaults_header""$defaults_list" | $pager 2>/dev/null
    fi
}

function self_upgrade() {
    # upgrade the running xsrv script in-place
    script_path="$0"
    echo "[xsrv] INFO fetching latest release..."
    if [[ -d "$xsrv_clone_dir/.git" ]]; then
       git -C "$xsrv_clone_dir" pull
       git -C "$xsrv_clone_dir" checkout "$xsrv_upgrade_channel"
    else
      git clone -b "$xsrv_upgrade_channel" "$xsrv_git_url" "$xsrv_clone_dir"
    fi
    new_version="$(grep '^version=.*' "$xsrv_clone_dir/xsrv" | cut -d= -f2)"
    new_commit="$(git -C "$xsrv_clone_dir" rev-parse HEAD)"
    read -r -p "[xsrv] INFO: this will upgrade the script at $script_path ($version) to $new_version ($new_commit). Type YES to confirm: " confirm_upgrade
    if [[ "$confirm_upgrade" == "YES" ]]; then
        if [[ -w "$script_path" ]]; then
            echo "[xsrv] INFO: $script_path is writeable"
            cp "$xsrv_clone_dir/xsrv" "$script_path"
            echo "[xsrv] INFO: upgrade complete"
            exit 0
        else
            echo "[xsrv] INFO: $script_path is not writeable. Upgrading with sudo"
            sudo cp -v "$xsrv_clone_dir/xsrv" "$script_path"
            echo "[xsrv] INFO: upgrade complete"
            exit 0
        fi
    else
        echo "[xsrv] ERROR: did not enter YES, aborting"
        exit 1
    fi
}

function format_ansible_tags() {
    # format ansible-playbook --list tags output as a list, one item per line
    grep 'TASK TAGS:' | sed 's/      TASK TAGS: \[//' | sed 's/\]$//' | sed 's/, /\n/g' | sort --unique
}

function help_tags() {
    # show the list of tags and their descriptions
    check_project_exists
    cd "$projects_dir/$project_name"
    echo "[xsrv] INFO: list of tags in project $project_name"
    echo "[xsrv] USAGE: TAGS=tag1,tag2,tag3 xsrv deploy $project_name"
    tags_doc=$(grep --no-filename '^# @tag' ansible_collections/*/*/roles/*/meta/main.yml | \
        cut -d " " -f 1-2 --complement | \
        sort --unique)
    echo "TAGS:"
    echo "$tags_doc"
    tags_doc_short=$(echo "$tags_doc" | cut -d " " -f 1 | sort --unique)
    tags_discovered_all=$(ansible-playbook playbook.yml --list-tags --tags never,all | format_ansible_tags )
    echo "OTHER TAGS:"
    diff --changed-group-format='%<%>' --unchanged-group-format='' <(echo "$tags_doc_short") <(echo "$tags_discovered_all")
}


############################

function _main() {
    echo "$ascii_banner"
    if [[ -z "$command" ]]; then echo "[xsrv] ERROR: no command provided"; echo "$usage"; exit 1; fi
    case "$command" in
        "init-project") shift; init_project ;;
        "init-host") init_venv; shift; init_host ;;
        "deploy") check_project_exists; init_venv; shift; deploy ;;
        "check") init_venv; shift; check ;;
        "edit-playbook") shift; edit_playbook ;;
        "edit-inventory") shift; edit_inventory ;;
        "edit-requirements") shift; edit_requirements;;
        "edit-cfg") shift; edit_ansible_cfg;;
        "edit-host") shift; edit_host ;;
        "edit-group") shift; edit_group;;
        "edit-vault") init_venv; shift; edit_vault ;;
        "shell") init_venv; shift; run_shell ;;
        "logs") init_venv; shift; ssh_args="bash -c 'if [[ -r /var/log/syslog ]]; then lnav /var/log/syslog; else sudo lnav /var/log/syslog; fi'"; run_shell ;;
        "ls") shift; _ls "$@" ;;
        "help") echo "$usage" ;;
        "help-tags") init_venv; shift; help_tags ;;
        "fetch-backups") init_venv; shift; fetch_backups ;;
        "upgrade") init_venv; shift; upgrade_roles ;;
        "show-defaults") shift; show_defaults "$@";;
        "self-upgrade") self_upgrade;;
        "init-playbook") init_venv; shift; legacy_init_playbook;;
        *) echo "[xsrv] ERROR: unrecognized command $command"; exit 1 ;;
    esac
}


############################

# Usage
usage="
USAGE: xsrv COMMAND [project] [host]

init-project [project] [host]   initialize a new project (and optionally a first host)
edit-inventory [project]        edit/show inventory file (hosts/groups)
edit-playbook [project]         edit/show playbook (roles for each host)
show-defaults [project] [role]  show all variables and their default values
edit-requirements [project]     edit ansible requirements/collections
edit-cfg [project]              edit ansible configuration (ansible.cfg)
init-host [project] [host]      add a new host to an existing project
check [project] [host]          simulate deployment, report what would be changed
deploy [project] [host]         deploy the main playbook in a project (apply configuration/roles)
edit-host [project] [host]      edit host configuration (host_vars)
edit-vault [project] [host]     edit encrypted (vault) host configuration (host_vars)
edit-group [project] [group]    edit group configuration (default group: all) (group_vars)
fetch-backups [project] [host]  fetch backups from a host to the local backups directory
shell [project] [host]          open interactive shell on a host
logs [project] [host]           view system logs on a host
ls                              list files in the projects directory (accepts a path)
help                            show this message
help-tags [project]             show the list of ansible tags and their descriptions
upgrade [project]               upgrade roles/collections to latest versions
self-upgrade                    check for new releases/upgrade the xsrv script in-place

# ENVIRONMENT VARIABLES (usage: VARIABLE=VALUE xsrv COMMAND)
TAGS               deploy/check only: list of ansible tags (TAGS=ssh,samba,... xsrv deploy)
EDITOR             text editor to use (default: nano)
PAGER              pager to use (default: nano --syntax=YAML --view +1 -)

# DOCUMENTATION
https://xsrv.readthedocs.io/en/master/usage.html
"

command="${1:-}"
project_name="${2:-default}"
project_dir="$projects_dir/$project_name"
venv_dir="$project_dir/.venv"
host_name="${3:-}"
ssh_args=""

_main "$@"
