#!/bin/bash
# Description: finds paths to all php-fpm pools sockets, and adds them to the 
#              PHP_FPM_SCRAPE_URI environment variable in /etc/prometheus/php-fpm-exporter.env
echo "INFO: building prometheus-php-fpm-exporter configuration"
fpm_status_paths=$(grep -r '^listen = /run/php/' /etc/php/*/fpm/pool.d | cut -d' ' -f -2 --complement | while read path; do echo -n "unix://${path};/.fpm-status,"; done)
echo "PHP_FPM_SCRAPE_URI=$fpm_status_paths" > /etc/prometheus/php-fpm-exporter.env
