#!/bin/bash
# Parse needrestart output and reboot automatically if needed.
# Must be run as root or user with permissions to reboot.
set -o errexit
set -o pipefail
set -o nounset

needrestart_ksta=$(/usr/sbin/needrestart -b -k | grep '^NEEDRESTART-KSTA' | awk -F' ' '{print $2}')

if [[ "$needrestart_ksta" == "3" ]]; then
    echo "NEEDRESTART-KSTA: 3, reboot required, rebooting"
    /usr/sbin/reboot
elif [[ "$needrestart_ksta" == "2" ]]; then
    echo "NEEDRESTART-KSTA: 2, reboot required, rebooting"
    /usr/sbin/reboot
else
    echo "No reboot required."
fi
