- name: import victoriametrics installation tasks
  become: yes
  import_tasks: victoriametrics.yml
  tags:
    - victoriametrics
    - monitoring

- name: import ansible facts configuration tasks
  import_tasks: fact.yml
  become: yes
  tags: gitea
