### NEEDRESTART AUTORESTART ###

- name: install needrestart
  apt:
    state: present
    package: needrestart
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
    - common
    - needrestart

- name: configure needrestart autorestart
  template:
    src: "etc_needrestart_conf.d_autorestart.conf.j2"
    dest: "/etc/needrestart/conf.d/autorestart.conf"
    mode: "0600"
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
    - common
    - needrestart

- name: copy needrestart automatic reboot script
  copy:
    src: usr_local_bin_needrestart-autorestart
    dest: /usr/local/bin/needrestart-autorestart
    owner: root
    group: root
    mode: "0755"
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
    - common
    - needrestart

- name: setup needrestart cron job
  template:
    src: etc_cron.d_needrestart-autorestart.j2
    dest: /etc/cron.d/needrestart-autorestart
    owner: root
    group: root
    mode: "0644"
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
    - common
    - needrestart
