- name: restart php-fpm (tt_rss)
  service:
    name: php{{ tt_rss_php_fpm_version }}-fpm
    state: restarted
    enabled: yes
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"

- name: restart tt-rss update timer
  become: yes
  systemd:
    name: tt-rss-update.timer
    state: restarted
    enabled: yes
  ignore_errors: "{{ ansible_check_mode }}"
