##### MONITORING.EXPORTERS #####
# uninstall netdata and remove all its files/data/configuration
netdata_uninstall: true
# REQUIRED password used to authenticate to/scrape metrics from exporter-exporter
monitoring_exporters_auth_password: CHANGEME
# log level for prometheus-blackbox-exporter (info/debug/warn/error)
exporters_blackbox_log_level: warn
# URL of the central VictoriaMetrics instance for remote write
# Example: https://monitoring.example.com:8428
monitoring_victoriametrics_url: "CHANGEME"
# list of URLs to probe via blackbox-exporter HTTP checks from this host
# Example: [https://example.com, https://other.com]
exporters_blackbox_http_checks: []
# list of host:port targets to probe via blackbox-exporter TCP checks (tcp_connect module) from this host
# Example: [ldap.example.org:636, ldap.example.org:389]
exporters_blackbox_tcp_checks: []
