- name: create wireguard config directory on the controller
  become: no
  delegate_to: localhost
  file:
    path: "{{ playbook_dir }}/data/wireguard/{{ inventory_hostname }}"
    state: directory
    mode: "0755"

- name: download wireguard peer client configs to the controller
  become: true
  fetch:
    src: /etc/wireguard/peers/client-config/{{ item.name }}.conf
    dest: "{{ playbook_dir }}/data/wireguard/{{ inventory_hostname }}/{{ item.name }}.conf"
    flat: no
  when: (item.state is not defined) or (item.state == 'present')
  loop: "{{ wireguard_peers }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: download wireguard peer QR codes to the controller
  become: true
  fetch:
    src: /etc/wireguard/peers/client-config/{{ item.name }}.qrcode
    dest: "{{ playbook_dir }}/data/wireguard/{{ inventory_hostname }}/{{ item.name }}.qrcode"
    flat: no
  when: (item.state is not defined) or (item.state == 'present')
  loop: "{{ wireguard_peers }}"
  ignore_errors: "{{ ansible_check_mode }}"
