name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Install system dependencies
        run: make test_install_test_deps
      - name: Install Python dependencies
        run: make venv
      - name: Run tests
        run: make tests
